// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDNBBbfDl-TcmxHug-vM5RGFonM-KTQCg',
    appId: '1:276924770963:web:bc99c6c9db4320becf3b66',
    messagingSenderId: '276924770963',
    projectId: 'note-c1d28',
    authDomain: 'note-c1d28.firebaseapp.com',
    storageBucket: 'note-c1d28.firebasestorage.app',
    measurementId: 'G-D1QM1R1Q4B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCl-ixMmjlzHgXup0FBqpfPNyQROA1I3B8',
    appId: '1:276924770963:android:e0d0823755a287d3cf3b66',
    messagingSenderId: '276924770963',
    projectId: 'note-c1d28',
    storageBucket: 'note-c1d28.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOptvwm3wo6P91L0YtOZdVARCuo_dsaVk',
    appId: '1:276924770963:ios:4fc836e4ed76124ccf3b66',
    messagingSenderId: '276924770963',
    projectId: 'note-c1d28',
    storageBucket: 'note-c1d28.firebasestorage.app',
    iosBundleId: 'com.example.note',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOptvwm3wo6P91L0YtOZdVARCuo_dsaVk',
    appId: '1:276924770963:ios:4fc836e4ed76124ccf3b66',
    messagingSenderId: '276924770963',
    projectId: 'note-c1d28',
    storageBucket: 'note-c1d28.firebasestorage.app',
    iosBundleId: 'com.example.note',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDDNBBbfDl-TcmxHug-vM5RGFonM-KTQCg',
    appId: '1:276924770963:web:475b05974a44e6c7cf3b66',
    messagingSenderId: '276924770963',
    projectId: 'note-c1d28',
    authDomain: 'note-c1d28.firebaseapp.com',
    storageBucket: 'note-c1d28.firebasestorage.app',
    measurementId: 'G-EK3PSKLMCJ',
  );
}
